### ISSUE TITLE
LinkedIn Mobile SDK Deprecation

### ISSUE THREAD

**Issue by nicky-ernste** [jzeferino/Xamarin.LinkedIn#20]
It seems that linkedIn has decided that with the launch of their new 2.0 API that they will deprecate the mobile SDK's including the one that is used by this Xamarin Binding Library.

As far as i can tell they don't plan on updating the SDK's so logging in via the LinkedIn app seems like it won't be possible anymore.
See [https://engineering.linkedin.com/blog/2018/12/developer-program-updates](https://engineering.linkedin.com/blog/2018/12/developer-program-updates)

They are forcing everyone to use the OAuth2 flow with the web page to login. Also the r_basicprofile scope will not be available anymore but only the r_liteprofile which has only the following data:
- First name
- Last name
- Email address
- Profile picture

Also see the [LinkedIn migration guide](https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq?context=linkedin/consumer/context)

So sadly i'm not sure if this plugin can still be used to authenticate with LinkedIn in the future.

**Comment by jzeferino** [comment]
> SDKs: Our JavaScript and Mobile Software Development Kits (SDKs) will stop working. Developers will need to migrate to using OAuth 2.0 directly from their apps. 

So, this means the end for this project. 👎

**Comment by nicky-ernste** [comment]
Seems like it yeah...
I was using it in an app and now have to change that quick.

For what it's worth. I enjoyed using your library.
